
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A CandyPink Blog
email: candypink@outlook.it
description: >- # this means to ignore newlines until "baseurl:"
  A CandyPink blog is a space for me to share my learning path in data science 
  and write posts on basically anything I fancy. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  candypink

# Build settings
markdown: kramdown
remote_theme: candypink/jekyll-theme-candypink
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


collections:
  projects:


navigation:
  - name: Blog 
    link: /blog/index.html
  - name: Portfolio
    link: /portfolio.html
  - name: About
    link: /about.html


paginate: 3
paginate_path: "/blog/page:num/"


